name: validate-reusable

on:
  workflow_call:
    inputs:
      schema:
        required: true
        type: string

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: diff
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            BASE="${{ github.event.pull_request.base.sha }}"
          else
            BASE=$(git rev-parse HEAD~1)
          fi

          MODIFIED=$(git diff --name-only "$BASE" HEAD \
            | grep -E '^sources/.*\.(md|ya?ml|json)$' || true)

          echo "files<<EOF" >> "$GITHUB_OUTPUT"
          echo "$MODIFIED" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Run validator
        if: steps.diff.outputs.files != ''
        run: |
          FILES="${{ steps.diff.outputs.files }}"
          FILES="${FILES//$'\n'/ }"
          npx @migiwa-ya/data-validator $FILES --schema schema.json

      - name: No changes
        if: steps.diff.outputs.files == ''
        run: echo "No source changes detected; skipping validation."
